name: dbt_analytics_engineering
version: 1.0.0
config-version: 2

profile: dbt_analytics_engineering

require-dbt-version: [">=1.8.0", "<2.0.0"]

flags:
  dbt_sqlserver_use_native_string_types: true
  dbt_sqlserver_use_default_schema_concat: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

vars:
  project_start_date: "2020-01-01"

models:
  dbt_analytics_engineering:

    staging:
      +materialized: view
      +tags: ["staging", "bronze"]

    intermediate:
      +materialized: table
      +tags: ["intermediate", "silver"]

    marts:
      +materialized: table
      +tags: ["marts", "gold"]

seeds:
  dbt_analytics_engineering:
    +schema: seeds

snapshots:
  dbt_analytics_engineering:
    +target_schema: snapshots
